branch-defaults:
  default:
    environment: Udagram1408221-env
    group_suffix: null
deploy:
  artifact: www/Archive.zip
global:
  application_name: udagram-140822-1
  branch: null
  default_ec2_keyname: vockey
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  repository: null
  sc: git
  workspace_type: Application
